### ISSUE TITLE
数据预处理的疑问

### ISSUE THREAD

**Issue by Voilett** [wyqing20/MMCLR#7]
论文中引用的论文写道：we filter out users and items with less than 5 purchase interactions，但是我下载本仓库中的数据集，发现有不少用户的购买次数小于5，想问问作者这个预处理规则到底是什么样的？

**Comment by wyqing20** [comment]
是这样的，因为物品和用户的过滤有一个顺序。比如过滤掉小于5的用户，剩下大于等于五的用户。再过滤掉小于五的物品，这时有部分用户的interaction会被过滤掉，所以会出现小于5的用户。

**Comment by Voilett** [comment]
> 

我按照先用户后物品的顺序，过滤后用户数量还有十几万...
