### ISSUE TITLE
您好，训练图和测试图是如何划分的？

### ISSUE THREAD

**Issue by Voilett** [wyqing20/MMCLR#8]
我发现测试图的各行为数量是符合论文中的统计，由于我刚接触推荐系统，所以不明白训练图为何去掉了辅助行为的部分边，而没有去掉目标行为的边，其又是如何去掉的？
另外，我分析了train_seq的数据，不管是原始数据还是按单行为去重，似乎和论文中的统计都对不上？

**Comment by wyqing20** [comment]
您好，感谢您的关注，
这里使用数据的方式是这样的。 例如：u1的行为序列为 click_1->cart_1->buy_2 -> click_3 ->buy_5-> cart_4. 那么我们在预测buy_5行为的时候就会丢掉 cart_4。因为这是发生在 buy2之后的。 对于train_seq这一操作我是在生成样本的时候动态处理的。 对于graph由于边没有时间信息。故我将其预处理了, 假如我们将 buy_5划入测试集，那么 对于train_graph 对于 u1来说其包括了 click1, cart_1,buy_2. 对于 test graph 其包括了click1, cart_1,buy_2，click 3。 这是为什么造成了train_seq和 论文中的对不上，和去除部分边。

**Comment by Voilett** [comment]
> 您好，感谢您的关注， 这里使用数据的方式是这样的。 例如：u1的行为序列为 click_1->cart_1->buy_2 -> click_3 ->buy_5-> cart_4. 那么我们在预测buy_5行为的时候就会丢掉 cart_4。因为这是发生在 buy2之后的。 对于train_seq这一操作我是在生成样本的时候动态处理的。 对于graph由于边没有时间信息。故我将其预处理了, 假如我们将 buy_5划入测试集，那么 对于train_graph 对于 u1来说其包括了 click1, cart_1,buy_2. 对于 test graph 其包括了click1, cart_1,buy_2，click 3。 这是为什么造成了train_seq和 论文中的对不上，和去除部分边。

非常感谢！
